.\" Copyright (c) 1980, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     from: @(#)fingerd.8	6.4 (Berkeley) 3/16/91
.\"	$Id: fingerd.8,v 1.18 2000/07/30 23:56:57 dholland Exp $
.\"
.Dd August 29, 1996
.Dt FINGERD 8
.Os "Linux NetKit (0.17)"
.Sh NAME
.Nm fingerd
.Nd remote user information server
.Sh SYNOPSIS
.Nm fingerd
.Op Fl wulf
.Op Fl pL Ar path
.Op Fl t Ar timeout
.Sh DESCRIPTION
.Nm Fingerd
is a simple daemon based on
.%T RFC1196
that provides an interface to the
.Dq finger
program at most network sites.
The program is supposed to return a friendly,
human-oriented status report on either the system at the moment
or a particular person in depth. 
.Pp
If the
.Fl w
option is given, remote users will get an additional 
.Dq Welcome to ...
banner
which also shows some informations (e.g. uptime, operating system name and
release) about the system the
.Nm fingerd
is running on. Some sites may consider this a security risk as it
gives out information that may be useful to crackers. 
.Pp
If the 
.Fl u
option is given, requests of the form
.Dq finger @host
are rejected.
.Pp
If the
.Fl l
option is given, information about requests made is logged. This
option probably violates users' privacy and should not be used on
multiuser boxes.
.Pp
If the
.Fl f
option is given, finger forwarding (user@host1@host2) is allowed.
Useful behind firewalls, but probably not wise for security and
resource reasons.
.Pp
The 
.Fl p
option allows specification of an alternate location for fingerd to find
the 
.Dq finger
program. The
.Fl L
option is equivalent.
.Pp
The
.Fl t
option specifies the time to wait for a request before closing the
connection.  A value of 0 waits forever.  The default is 60 seconds.
.Pp
Options to fingerd should be specified in 
.Pa /etc/inetd.conf .
.Pp
The finger protocol consists mostly of specifying command arguments.
The 
.Xr inetd 8
.Dq super-server
runs
.Nm fingerd
for 
.Tn TCP
requests received on port 79.
Once connected 
.Nm fingerd
reads a single command line
terminated by a
.Aq Tn CRLF
which is passed to
.Xr finger 1 .
It closes its connections as soon as all output is finished.
.Pp
If the line is empty (i.e. just a
.Aq Tn CRLF
is sent) then 
.Xr finger
returns a
.Dq default
report that lists all people logged into
the system at that moment. This feature is blocked by the 
.Fl u
option.
.Pp
If a user name is specified (e.g.
.Pf eric Aq Tn CRLF )
then the
response lists more extended information for only that particular user,
whether logged in or not.
Allowable
.Dq names
in the command line include both
.Dq login names
and
.Dq user names .
If a name is ambiguous, all possible derivations are returned.
.Sh SEE ALSO
.Xr finger 1 ,
.Xr inetd 8
.Sh RESTRICTIONS
Connecting directly to the server from a
.Tn TIP
or an equally narrow-minded
.Tn TELNET Ns \-protocol
user program can result
in meaningless attempts at option negotiation being sent to the
server, which will foul up the command line interpretation.
.Sh HISTORY
The finger daemon appeared in
.Bx 4.3 .
